// Ride descriptions copied verbatim from each Notion climb page's # Description
// ("List of climbs") for routes that haven't had a full ride sync yet. A synced
// route gets its blurb from its generated rideScripts/<id>.ts instead — once a
// route is synced, drop it from here. Don't reword: Leonard edits these in Notion.
export const RIDE_BLURBS: Record<string, string> = {
  jirisan: "Long, steady climbs through dense forest over the high passes of Korea's first national park.",
  "suncheon-bay": "Rolling coastal and farm roads around one of Korea's largest reed wetlands. A day for distance, not big climbs.",
  "jeju-round": "An epic 225 km adventure around the beautiful island of Jeju, with stops at a nice café and a restaurant serving really good stir-fried octopus.",
  "jeju-volcano": "A loop through thick forest around Hallasan, passing through the two high points of 1100 Highland and Seongpanak.",
  "jeju-western": "From Seogwipo into the forests of Hallasan, then sweeping down towards Aewol and the sea again. A little mountain adventure, taking the long way back through Jeju’s quieter west.",
  hwaaksan: "From Seoul to Gapyeong, following the Han River, then up Hwaaksan—a brutal climb with gradients often over 10%. Back down the same road, then a well-earned train ride back to Seoul.",
  "that-busan-route": "A punishing day in the mountains around Busan, with tough, steep climbs coming one after another right from the start. Watch out for Eden Valley.",
  dolsan: "Rolling shoreline roads around an island off Yeosu, with sea views nearly the whole way.",
  taebaeksan: "West from Taebaek through towns and quiet mountain roads, with the Taebaek Mountains all around and a climb over Manhangjae towards the end. One of those days when climbing is a joy.",
  daegwallyeong: "A glorious climb from Gangneung up Daegwallyeong on wide, beautifully maintained roads—some of the best tarmac I’ve ridden. Then north towards Jingogae before looping back to Gangneung.",
  "shibu-touge": "One of the most picturesque climbs I’ve ever done, past sulphur vents and into open alpine scenery, all the way to the highest point on Japan’s national road network.",
  "haruna-akagi": "Mount Haruna and Mount Akagi—two iconic Japanese volcanoes, with crater lakes and hairpin roads made famous by Initial D. An epic day in the mountains.",
  "nikko-highland": "Irohazaka, another Initial D legend: 48 hairpins, a further climb to Lake Chūzenji, and panoramic highland views at the top. Watch out for bears in the forest.",
  utsukushigahara: "One of the most amazing rides I’ve ever done. A ribbon of road carved through the mountains, with unobstructed views stretching from one range to the next. There aren’t many roads like this.",
  "tsumago-juku": "Through forested hills to a preserved Edo-period post town on the old Nakasendo. A rest-day ride with a destination.",
  "shirabiso-pass": "A big day of climbing on remote, rugged forest roads, with hardly a car in sight. Incredible views of the Southern Alps await at the top. There’s a special feeling to this place.",
  "yanagisawa-pass": "The old road linking Tokyo and Yamanashi, now a cycling paradise. A long, steady climb, with a glimpse of Mount Fuji if you’re lucky.",
  "ebino-plateau": "Up through forest to a volcanic plateau of steaming vents and crater lakes in the Kirishima mountains.",
  "miyazaki-castle": "Forgotten forest roads and castles atop hills. A ride through the history and quiet magic of Kyushu.",
  "ibusuki-skyline": "From Kagoshima along the coast to Kaimondake, then back through the mountains on the Ibusuki Skyline. A day with the best of both coast and mountains.",
  sakurajima: "A ferry ride to Sakurajima, then a full lap around one of the world’s most active volcanoes before taking the ferry back to Kagoshima.",
  "maruo-falls": "A quick training loop around the Kirishima volcano cluster, with a little waterfall stop along the way.",
  "mt-aso": "Up and along the rim of one of the world’s largest calderas, then down into it and up to the volcano at its heart. A spring ride surrounded by cherry blossoms.",
  "mt-unzen": "A ferry from Kumamoto to Shimabara, then a day devoted to climbing Mount Unzen. One of the pure climbing days of my spring trip through Japan.",
  "kusenbuyama-sefuri": "Just outside Fukuoka, yet surprisingly remote once you’re in the mountains. A memorable ride on forest roads, with an ancient shrine waiting at the top of Mount Sefuri.",
  "mt-wanitsuka": "One of the hidden gems I found in Kyushu. A pure climbing day on rugged forest roads, without a car in sight, with panoramic views waiting at the radio tower at the top.",
  "wuling-west": "Past Cingjing's farms into the alpine zone, up to the highest road in Taiwan. The gentler side of Wuling, still a huge day.",
  yangmingshan: "Taipei’s go-to training climbs, past sulphur vents and grassy ridges.",
  "taiwan-kom": "One of the toughest rides I’ve ever done. 3,250 metres of climbing, from the beautiful, rugged Taroko Gorge all the way up to Wuling Pass. Even collected a cookie at the end.",
  "taipei-northern": "Over the mountains to Taiwan's rocky north coast and its fishing towns, then back into the city.",
  "ku-ring-gai": "Steady climbs out of the inlets at Bobbin Head and Akuna Bay, with bushland the whole way. A Sydney classic.",
  "royal-np": "Coastal bushland and rolling park roads through the world's second-oldest national park, south of Sydney.",
  "lantau-island": "Quiet mountain roads on Lantau, a world away from the city. Then comes the Beast—a climb that lives up to its name.",
}
