// GENERATED by tools/sync-ride.py from content/rides/namhansanseong.md — a snapshot
// of Leonard's Notion page. Don't edit by hand: change the page, re-snapshot, re-sync.
import type { ScriptLine } from '../worlds'

export const script: ScriptLine[] = [
  { say: "Namhansanseong is a historic mountain fortress city located 25 kilometres southeast of Seoul in Gyeonggi Province, South Korea." },
  { say: "This trip happened in 2022. I just picked up cycling and I knew I wanted to travel around with my bike." },
  { say: "From Myeongdong, I made my way to the Han River before heading south towards Seongnam." },
  { say: "From there, I entered Namhansanseong from the southern gate.", photos: ["/blog/namhansanseong/images/9e4bd07d.jpg"] },
  { say: "The start was very pretty steep. The grade was consistently at 10%+.", photos: ["/blog/namhansanseong/images/bc0bfc0b.jpg"] },
  { say: "It was a jacket on, jacket off, situation for me.", photos: ["/blog/namhansanseong/images/e290f78b.jpg"] },
  { say: "I felt the early spring chill again when the gradient eased up. Had to put on the jacket again.", photos: ["/blog/namhansanseong/images/c2c52f82.jpg"] },
  { say: "I arrived at the bottom of the fortress. There is a hanok village. It was beautiful.", photos: ["/blog/namhansanseong/images/55c2c70d.jpg"] },
  { say: "You cannot cycle around the fortress area. So, I dismount from the bike and started walking instead.", photos: ["/blog/namhansanseong/images/f31dbb34.jpg"] },
  { say: "Namhansanseong wasn’t a difficult mountain to climb and I think it’s definitely a historical site worth visiting. I might want to do hike up here next time!", photos: ["/blog/namhansanseong/images/068a3927.jpg"] },
  { say: "Cherry Blossom roads on my way back to Seoul.", photos: ["/blog/namhansanseong/images/f1d42cde.jpg"] },
]
