// GENERATED by tools/sync-ride.py from content/rides/namsan-bugaksan.md — a snapshot
// of Leonard's Notion page. Don't edit by hand: change the page, re-snapshot, re-sync.
import type { ScriptLine } from '../worlds'

export const script: ScriptLine[] = [
  { say: "10 April, 2022. Right at the end of COVID-19." },
  { say: "Travel restrictions are easing, and countries are finally opening up their borders.", photos: ["/blog/namsan-bugaksan/images/05204386.jpg"] },
  { say: "It was intense back then as a Singaporean. The island city paradise became an island prison. During the lockdown, we were all trapped here." },
  { say: "Towards the end of 2021, I picked up cycling.", photos: ["/blog/namsan-bugaksan/images/2d6386b0.jpg"] },
  { say: "I immediately knew this was my next sport. It had everything." },
  { say: "I could train, compete, and the thing that excites the most – I could explore." },
  { say: "I cycled with a few colleagues in those early days and we explored Singapore.", photos: ["/blog/namsan-bugaksan/images/042e3481.jpg"] },
  { say: "There’s so much more to see and I can do so much with my bike." },
  { say: "That was the start of everything.", photos: ["/blog/namsan-bugaksan/images/f0adb61c.jpg"] },
  { say: "Korea was one of the few countries that opened up first. My wife and I have never been there, so, why not?", photos: ["/blog/namsan-bugaksan/images/bc519b8f.jpg"] },
  { say: "Looking back, I wasn’t sure what I was getting myself into. I just dived in head first." },
  { say: "I created a few routes on Strava, and that was it." },
  { say: "I brought my Elves Vanyar with me. It’s a chinese rim brake bike. I built it myself. That’s also how I became independent when it comes to bike maintenance.", photos: ["/blog/namsan-bugaksan/images/2046cb46.jpg"] },
  { say: "I think I was one of the earliest adopters of using a 360 camera on a bike.", photos: ["/blog/namsan-bugaksan/images/705400d3.jpg"] },
  { say: "This was back in 2022. The Insta360 X2 was held by a clamp on the handlebar. This photo was taken at the end of this ride. At the top of Bugaksan.", photos: ["/blog/namsan-bugaksan/images/b9fe0149.jpg"] },
  { say: "This route is a short ride in Seoul. It takes you first to Namsan, which was crazy beautiful in Spring when the Cherry Blossoms are in full bloom.", photos: ["/blog/namsan-bugaksan/images/d2b653fa.jpg", "/blog/namsan-bugaksan/images/8b79f5d8.jpg"] },
  { say: "The route then takes us towards Bugaksan, just behind the historic Gyeongbokgung Palace.", photos: ["/blog/namsan-bugaksan/images/59c6ba6d.jpg"] },
  { say: "I don’t recall the Bugaksan climb to be visually spectacular.", photos: ["/blog/namsan-bugaksan/images/d0b353c1.jpg", "/blog/namsan-bugaksan/images/83f8c983.jpg"] },
  { say: "Skip it if you want, but if you want a quick ride around Seoul, you can consider adding it into your plan.", photos: ["/blog/namsan-bugaksan/images/bb451eb2.jpg"] },
]
