// GENERATED by tools/sync-ride.py from content/rides/tai-mo-shan.md — a snapshot
// of Leonard's Notion page. Don't edit by hand: change the page, re-snapshot, re-sync.
import type { ScriptLine } from '../worlds'

export const script: ScriptLine[] = [
  { say: "Hong Kong gives me anxiety." },
  { say: "It feels a lot like Singapore, except that you jam a lot more people in.", photos: ["/blog/tai-mo-shan/images/9712ee87.jpg"] },
  { say: "The buildings are taller, the streets are busier, and the drivers.. they are super aggressive. Not a good recipe for a road cyclist." },
  { say: "I came here after winning the Masters Esports Singapore National Championships. I wanted to take a short break.", photos: ["/blog/tai-mo-shan/images/b3e915f2.jpg"] },
  { say: "And also meet with my aunt who I haven’t met in more than a decade.", photos: ["/blog/tai-mo-shan/images/9ae17a48.jpg"] },
  { say: "And also to spend some time with my wife who’s been really supportive in this cycling journey.", photos: ["/blog/tai-mo-shan/images/655c3015.jpg"] },
  { say: "The Dragon’s Back hike, amazing btw.", photos: ["/blog/tai-mo-shan/images/c65b7287.jpg"] },
  { say: "I also shamelessly brought my bike with me. Why not?", photos: ["/blog/tai-mo-shan/images/fb757aa6.jpg"] },
  { say: "I learned about Tai Mo Shan while researching about Hong Kong’s viability as a cycling destination. If there’s a mountain, I want to climb it.", photos: ["/blog/tai-mo-shan/images/bf6ab2d8.jpg"] },
  { say: "I started the ride early to avoid the notorious Hong Kong traffic. It was a good decision." },
  { say: "Once I got away from the city, the roads became clear. This was a rare sight in Hong Kong.", photos: ["/blog/tai-mo-shan/images/3d236f61.jpg"] },
  { say: "The tarmac ended and I found myself in the back roads of rural Hong Kong.", photos: ["/blog/tai-mo-shan/images/8613a92c.jpg"] },
  { say: "Tai Lam Chung Reservoir Dam.", photos: ["/blog/tai-mo-shan/images/4f4a91d1.jpg"] },
  { say: "After the reservoir, it was mostly park roads. More like it was built for walking than cycling.", photos: ["/blog/tai-mo-shan/images/391ed3bd.jpg"] },
  { say: "It was also subjected to the area’s micro-climate.", photos: ["/blog/tai-mo-shan/images/9769f756.jpg"] },
  { say: "Just like in Korea, the elders love a hike. Instead of “Anyeonghasaeyo”, you say “Zou san”, which means “good morning” in Cantonese.", photos: ["/blog/tai-mo-shan/images/8775b39d.jpg"] },
  { say: "After what seemed like a really long lead-in to Tai Mo Shan, the dense forest finally gave way.", photos: ["/blog/tai-mo-shan/images/5c0244ed.jpg"] },
  { say: "I could see the mountains.", photos: ["/blog/tai-mo-shan/images/bc3fe5ec.jpg"] },
  { say: "..and buffalos. Definitely wasn’t expecting that.", photos: ["/blog/tai-mo-shan/images/3dd40875.jpg"] },
  { say: "The finish point is the iconic observatory at the top of the mountain.", photos: ["/blog/tai-mo-shan/images/e866dccf.jpg"] },
  { say: "The final stretches of the road were amazing. It felt like a road to the sky.", photos: ["/blog/tai-mo-shan/images/7dc592b5.jpg"] },
  { say: "The views from the unguarded edge of the road added to the experience as well.", photos: ["/blog/tai-mo-shan/images/02b46c32.jpg"] },
]

/** The page's # Description — the pitch under the title in the selector + /blog/. */
export const blurb: string | undefined = "Past reservoirs and buffalo to Hong Kong's highest peak. The final stretch feels like a road to the sky."
